"""initial supplier network schema

Revision ID: 4d4ef4adb60c
Revises:
Create Date: 2026-09-06 12:29:51.792229
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d4ef4adb60c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_table('documents',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('event_logs',
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_actor_id'), 'event_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_event_logs_entity_id'), 'event_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_logs_entity_type'), 'event_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_occurred_at'), 'event_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_event_logs_organization_id'), 'event_logs', ['organization_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('import_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_organization_id'), 'import_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('products',
    sa.Column('created_by_organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_organization_id', 'brand', 'model', 'name', name='uq_product_supplier_brand_model_name')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_created_by_organization_id'), 'products', ['created_by_organization_id'], unique=False)
    op.create_index(op.f('ix_products_model'), 'products', ['model'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('supplier_profiles',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=240), nullable=False),
    sa.Column('unified_social_credit_code', sa.String(length=40), nullable=True),
    sa.Column('supplier_type', sa.String(length=40), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=60), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('cooperation_modes', sa.JSON(), nullable=False),
    sa.Column('export_markets', sa.JSON(), nullable=False),
    sa.Column('supports_dropshipping', sa.Boolean(), nullable=False),
    sa.Column('supports_oem', sa.Boolean(), nullable=False),
    sa.Column('has_export_experience', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('profile_completion', sa.Integer(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_profiles_organization_id'), 'supplier_profiles', ['organization_id'], unique=True)
    op.create_index(op.f('ix_supplier_profiles_status'), 'supplier_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_profiles_unified_social_credit_code'), 'supplier_profiles', ['unified_social_credit_code'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('supplier_applications',
    sa.Column('application_no', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=240), nullable=False),
    sa.Column('unified_social_credit_code', sa.String(length=40), nullable=True),
    sa.Column('company_type', sa.String(length=40), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('cooperation_modes', sa.JSON(), nullable=False),
    sa.Column('annual_revenue_range', sa.String(length=60), nullable=True),
    sa.Column('supports_dropshipping', sa.Boolean(), nullable=False),
    sa.Column('supports_oem', sa.Boolean(), nullable=False),
    sa.Column('has_export_experience', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('approved_organization_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_applications_application_no'), 'supplier_applications', ['application_no'], unique=True)
    op.create_index(op.f('ix_supplier_applications_approved_organization_id'), 'supplier_applications', ['approved_organization_id'], unique=False)
    op.create_index(op.f('ix_supplier_applications_reviewed_by_user_id'), 'supplier_applications', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_applications_status'), 'supplier_applications', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_applications_unified_social_credit_code'), 'supplier_applications', ['unified_social_credit_code'], unique=False)
    op.create_table('supplier_offers',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_sku', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('fulfillment_mode', sa.String(length=40), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'supplier_sku', name='uq_supplier_offer_sku')
    )
    op.create_index(op.f('ix_supplier_offers_organization_id'), 'supplier_offers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_product_id'), 'supplier_offers', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_status'), 'supplier_offers', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_offers_supplier_sku'), 'supplier_offers', ['supplier_sku'], unique=False)
    op.create_index(op.f('ix_supplier_offers_variant_id'), 'supplier_offers', ['variant_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshots_captured_at'), 'inventory_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_offer_id'), 'inventory_snapshots', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_snapshots_offer_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_captured_at'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_supplier_offers_variant_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_supplier_sku'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_status'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_product_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_organization_id'), table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_index(op.f('ix_supplier_applications_unified_social_credit_code'), table_name='supplier_applications')
    op.drop_index(op.f('ix_supplier_applications_status'), table_name='supplier_applications')
    op.drop_index(op.f('ix_supplier_applications_reviewed_by_user_id'), table_name='supplier_applications')
    op.drop_index(op.f('ix_supplier_applications_approved_organization_id'), table_name='supplier_applications')
    op.drop_index(op.f('ix_supplier_applications_application_no'), table_name='supplier_applications')
    op.drop_table('supplier_applications')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplier_profiles_unified_social_credit_code'), table_name='supplier_profiles')
    op.drop_index(op.f('ix_supplier_profiles_status'), table_name='supplier_profiles')
    op.drop_index(op.f('ix_supplier_profiles_organization_id'), table_name='supplier_profiles')
    op.drop_table('supplier_profiles')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_model'), table_name='products')
    op.drop_index(op.f('ix_products_created_by_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_organization_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_event_logs_organization_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_occurred_at'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_actor_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
